web5/urls.py
from django.contrib import admin
from django.urls import path

from app import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('depart/list/', views.depart_list),
    path('depart/add/', views.depart_add),
    path('depart/delete/', views.depart_delete),
    path('depart/<int:nid>/ebit/', views.depart_ebit),
    #

    path('role/list/', views.role_list),
    path('role/add/', views.role_add),
    path('role/delete/', views.role_delete),
    path('role/<int:nid>/ebit/', views.role_ebit),

    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('user/<int:nid>/delete/', views.user_delete),
    path('user/<int:nid>/ebit/', views.user_ebit),
]

app/models.py
from django.db import models


# Create your models here.
class Dept(models.Model):
    deptname = models.CharField(max_length=100)
    deptorder = models.IntegerField(verbose_name="order")
    status_choices = (
        (1, "normal"),
        (2, "Deactivate"),
    )
    status = models.SmallIntegerField(choices=status_choices)

    def __str__(self):
        return self.deptname


class Menu(models.Model):
    menuname = models.CharField(max_length=100)
    order_num = models.IntegerField
    path = models.CharField(max_length=100)
    status_choices = (
        (1, "normal"),
        (2, "Deactivate"),
    )
    status = models.SmallIntegerField(choices=status_choices)
    component = models.CharField(max_length=100)

    menu_type_choices = (
        (1, "Catalogue"),
        (2, "Menu"),
        (3, "Button"),
    )
    menu_type = models.SmallIntegerField(choices=menu_type_choices)


class Role(models.Model):
    role_name = models.CharField(max_length=50)

    data_scope_choices = (
        (1, "All"),
        (2, "NowDept"),
        (3, "Basic"),
    )

    data_scope = models.SmallIntegerField(choices=data_scope_choices)

    def __str__(self):
        return self.role_name

    status_choices = (
        (1, "normal"),
        (2, "Deactivate"),
    )
    status = models.SmallIntegerField(choices=status_choices)


class UserInfo(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=200)
    nick_name = models.CharField(max_length=50)
    age = models.IntegerField()

    user_type_choices = (
        (1, "system_user"),
        (2, "ordinary_user"),
    )
    usertype = models.SmallIntegerField(choices=user_type_choices)
    email = models.CharField(max_length=50)
    phonenumber = models.CharField(max_length=50)
    gender_choices = (
        (1, "male"),
        (2, "female"),
    )
    gender = models.SmallIntegerField(choices=gender_choices)
    create_time = models.DateField()
    employment_time = models.DateField()
    accoun_status_choices = (
        (1, "normal"),
        (2, "Deactivate"),
    )
    accoun_status = models.SmallIntegerField(choices=accoun_status_choices)

    depart = models.ForeignKey(to="Dept", to_field="id", on_delete=models.CASCADE)
    roles = models.ForeignKey(to="Role", to_field="id", on_delete=models.CASCADE)

templates/system/change.html
{% extends "base-left.html" %}
{% load static %}

{% block content %}
    <div class="container" style="width: 1300px;padding-top: 50px">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">{{ title }}</div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                        <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

templates/system/depart_list.html
{% extends "base-left.html" %}
{% load static %}

{% block content %}
    <div class="container" style="width: 1300px;padding-top: 50px">
        <div style="padding-bottom: 10px">
            <a class="btn btn-success" href="/depart/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Add Dept
            </a>
            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Dept List
            </div>
            <!-- Table -->
            <table class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Dept Name</th>
                    <th class="text-center">Dept Order</th>
                    <th class="text-center">Dept Status</th>
                    <th class="text-center">Manage</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th style="width: 90px" class="text-center" scope="row">
                            {{ item.id }}
                        </th>
                        <td class="text-center">{{ item.deptname }}</td>
                        <td class="text-center">{{ item.deptorder }}</td>
                        <td class="text-center">{{ item.get_status_display }}</td>
                        <td style="width: 150px" class="text-center">
                            <a class="btn btn-primary btn-xs" href="/depart/{{ item.id }}/ebit">update</a>
                            <a class="btn btn-danger btn-xs" href="/depart/delete?nid={{ item.id }}">delete</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

templates/system/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container" style="width: 1600px">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> Initiation point </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">Dept Manager</a></li>
                <li><a href="/user/list/">User Manager</a></li>
                <li><a href="/menu/list/">Menu Manager</a></li>
                <li><a href="/role/list/">Role Manager</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.session.info.name }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Personal</a></li>
                        <li><a href="#">My info</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">Sign up</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div>
    {% block content %}{% endblock %}
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>

{% block js %}{% endblock %}
</body>
</html>

templates/system/menu_list.html
{% extends "base-left.html" %}
{% load static %}

{% block content %}
    <div class="container" style="width: 1300px;padding-top: 50px">
        <div style="padding-bottom: 10px">
            <a class="btn btn-success" href="/menu/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Add Menu
            </a>
            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Role List
            </div>
            <!-- Table -->
            <table class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Menu Name</th>
                    <th class="text-center">Order Num</th>
                    <th class="text-center">Path</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Component</th>
                    <th class="text-center">Menu Type</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th style="width: 90px" class="text-center" scope="row">
                            {{ item.id }}
                        </th>
                        <td class="text-center">{{ item.menuname }}</td>
                        <td class="text-center">{{ item.order_num }}</td>
                        <td class="text-center">{{ item.path }}</td>
                        <td class="text-center">{{ item.get_status_display }}</td>
                        <td class="text-center">{{ item.component }}</td>
                        <td class="text-center">{{ item.get_menu_type_display }}</td>
                        <td style="width: 150px" class="text-center">
                            <a class="btn btn-primary btn-xs" href="/menu/{{ item.id }}/ebit">update</a>
                            <a class="btn btn-danger btn-xs" href="/menu/delete?nid={{ item.id }}">delete</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

templates/system/role_list.html
{% extends "base-left.html" %}
{% load static %}

{% block content %}
    <div class="container" style="width: 1300px;padding-top: 50px">
        <div style="padding-bottom: 10px">
            <a class="btn btn-success" href="/role/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Add Role
            </a>
            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Role List
            </div>
            <!-- Table -->
            <table class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Role Name</th>
                    <th class="text-center">Role scope</th>
                    <th class="text-center">Role Status</th>
                    <th class="text-center">Manage</th>
                </tr>
                </thead>
                <tbody>
                {% for item in queryset %}
                    <tr>
                        <th style="width: 90px" class="text-center" scope="row">
                            {{ item.id }}
                        </th>
                        <td class="text-center">{{ item.role_name }}</td>
                        <td class="text-center">{{ item.get_data_scope_display }}</td>
                        <td class="text-center">{{ item.get_status_display }}</td>
                        <td style="width: 150px" class="text-center">
                            <a class="btn btn-primary btn-xs" href="/role/{{ item.id }}/ebit">update</a>
                            <a class="btn btn-danger btn-xs" href="/role/delete?nid={{ item.id }}">delete</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

templates/system/user_add.html
{% extends "base-left.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container" style="width: 1300px;padding-top: 50px">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Add UserInfo </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block javascripts %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.en-AU.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_employment_time').datepicker({
                format: 'yyyy-mm-dd',
                language: "en-AU",
                autoclose: true
            });

        })
    </script>

    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                language: "en-AU",
                autoclose: true
            });

        })
    </script>
{% endblock %}

templates/system/user_edit.html
{% extends "base-left.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container" style="width: 1300px;padding-top: 50px">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> UserInfo </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" id="btn1">Submit</button>
                    <a id="btn2" href="/user/{{ request.session.info.id }}/ebit/" class="btn btn-primary">Change Info</a>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.en-AU.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_employment_time').datepicker({
                format: 'yyyy-mm-dd',
                language: "en-AU",
                autoclose: true
            });

        })

    </script>
    <script>

        window.onload = function () {
            if({{display}} == 1 ){
                $('#btn1').hide()
                $('#btn2').show();
            }
            if({{display}} == 2 ){
                $('#btn1').show();
                $('#btn2').hide();
            }
        }
    </script>

    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                language: "en-AU",
                autoclose: true
            });

        })
    </script>
{% endblock %}

templates/system/user_list.html
{% extends "base-left.html" %}
{% load static %}

{% block content %}
    <div class="container" style="width: 1300px;padding-top: 50px">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Add User
            </a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                UserInfo List
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">UserName</th>
                    <th class="text-center">Age</th>
                    <th class="text-center">User Type</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Phonen Number</th>
                    <th class="text-center">Gender</th>
                    <th class="text-center">Depart</th>
                    <th class="text-center">Role</th>
                    <th class="text-center">Accoun Status</th>
                    <th class="text-center">Employment Time</th>
                    <th class="text-center" style="width: 150px">Manage</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th style="width: 80px" class="text-center" scope="row">{{ obj.id }}</th>
                        <td class="text-center">{{ obj.username }}</td>
                        <td class="text-center">{{ obj.age }}</td>
                        <td class="text-center">{{ obj.get_usertype_display }}</td>
                        <td class="text-center">{{ obj.email }}</td>
                        <td class="text-center">{{ obj.phonenumber }}</td>
                        <td class="text-center">{{ obj.get_gender_display }}</td>
                        <td class="text-center">{{ obj.depart.deptname }}</td>
                        <td class="text-center">{{ obj.roles.role_name }}</td>
                        <td class="text-center">{{ obj.get_accoun_status_display }}</td>
                        <td class="text-center">{{ obj.employment_time|date:"Y-m-d" }}</td>
                        <td style="width: 180px" class="text-center">
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/ebit/">update</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">delete</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/reset/">Reset</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>
{% endblock %}